name: Container
on: push

jobs:
  node-docker:
    services:
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - "27017:27017"
    runs-on: ubuntu-latest
    steps:
      - name: Post A User 
        run: 'curl -X POST http://localhost:3001/api/user -H ''Content-Type: application/json'' -d ''{"username": "hello", "address": "dwded"}'''
      - name: Get User
        run: curl http://localhost:3001/api/user