name: Matrix
on: push

jobs:
  node-version:
    runs-on: ubuntu-latest
    steps:
      - name: Logs node-version Before
        run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: subdir/package-lock.json
      - name: Logs node-version After
        run: node -v