name: Matrix
on: push

jobs:
  node-version:
    strategy:
      fail-fast: true
      matrix:
        op: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [6, 10, 8]
    runs-on: ${{ matrix.op }}
    steps:
      - name: Logs node-version Before
        run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          # cache: 'npm'
          # cache-dependency-path: subdir/package-lock.json
      - name: Logs node-version After
        run: |
            node -v
